#!/bin/bash
#PBS -N VM2Dcp_Soldatova
#PBS -S /bin/bash
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=4
#PBS -d /home/marchevsky/VM2DcylPlate

cat $PBS_NODEFILE

mpirun -np 2 -map-by slot:pe=4 VM2D > log.log
